### ISSUE TITLE
0.9.0 not being installed

### ISSUE THREAD

**Issue by ErikEvenson** [mhahn/vagrant-librarian-puppet#34]
`vagrant plugin install vagrant-librarian-puppet` installs 0.8.0 -- not 0.9.0.

Is this because 0.9.0 hasn't been released in some way?

**Comment by mhahn** [comment]
0.9.0 has been published: https://rubygems.org/gems/vagrant-librarian-puppet

do you have bundler up to date?

**Comment by ErikEvenson** [comment]
Sorry, bundler?  I'm using Vagrant 1.7.2 pulled in via homebrew.

**Comment by mhahn** [comment]
vagrant uses bundler under the hood to manage plugins. it should take care of this for you though.

running:
`vagrant plugin install vagrant-librarian-puppet --plugin-version 0.9.0`

installs 0.9.0 for me, but I do see that it installs 0.8.0 otherwise.

I haven't been working with vagrant for awhile and am not going to have time to investigate right now.

**Comment by ErikEvenson** [comment]
Thanks Michael, that `--plugin-version` option worked for me and is a handy way to pin plugin versions in general.  Closing.

**Comment by mhahn** [comment]
Yea, I definitely recommend pinning all the plugins :). I've been screwed by that a few times.
